In [1]:

import numpy as np
import sympy as sp


In [3]:

def Pdsym(phi,theta): #goes from local to global
    return np.array([
        [(sp.cos(theta)*sp.cos(phi)).evalf(), (-sp.cos(theta)*sp.sin(phi)).evalf(), (sp.sin(theta)).evalf()],
        [sp.sin(phi).evalf(), sp.cos(phi).evalf(), 0],
        [(-sp.sin(theta)*sp.cos(phi)).evalf(), (sp.sin(theta)*sp.sin(phi)).evalf(), sp.cos(theta).evalf()]
    ])


In [4]:

def Pdnum(phi,theta): #goes from local to global
    return np.array([
        [np.cos(theta)*np.cos(phi), np.cos(theta)*np.sin(phi), -np.sin(theta)],
        [-np.sin(phi), np.cos(phi), 0],
        [np.sin(theta)*np.cos(phi), np.sin(theta)*np.sin(phi), np.cos(theta)]
    ])


In [5]:

def Pphi(phi):
       return np.array([
           [np.cos(phi),-np.sin(phi),0],
           [np.sin(phi),np.cos(phi),0],
           [0,0,1]
       ])

def Ptheta(theta):
    return np.array([
        [np.cos(theta),0,np.sin(theta)],
        [0,1,0],
        [-np.sin(theta),0,np.cos(theta)]
    ])

r = np.array([0,0,100])
phi = 90 * np.pi/180
theta = 90 * np.pi/180
Pp = Pphi(phi)
Pt = Ptheta(theta)

print(Pt @ Pp @ r)
print((Pt @ Pp) @ r)


[1.000000e+02 0.000000e+00 6.123234e-15]
[1.000000e+02 0.000000e+00 6.123234e-15]


In [6]:

phi = sp.rad(90)
theta = sp.rad(90)
print(Pdsym(phi,theta) @ r)


[100.000000000000 0 0]


In [7]:

phis = sp.rad(90)
thetas = sp.rad(45)
phin = 90 * np.pi/180
thetan = 45 * np.pi/180

Psym = Pdsym(phis,thetas)
print(Psym)
Pnum = Pdnum(phin,thetan)
print(Pnum)

M = np.array([0,0,1]) #in global
H = np.array([1,1,1]) #in local

one = Psym@H + M
two = Psym@(H + Psym.T@M)

print(two-one)


[[0 -0.707106781186548 0.707106781186548]
 [1.00000000000000 0 0]
 [0 0.707106781186548 0.707106781186548]]
[[ 4.32978028e-17  7.07106781e-01 -7.07106781e-01]
 [-1.00000000e+00  6.12323400e-17  0.00000000e+00]
 [ 4.32978028e-17  7.07106781e-01  7.07106781e-01]]
[0 0 0]


In [8]:

import sympy as sp
import time

def cos_deg_sympy(degrees):
    return float(sp.cos(sp.rad(degrees)).evalf())

start_time = time.time()
for _ in range(100000):
    cos_deg_sympy(90)
end_time = time.time()

print("SymPy time:", end_time - start_time)


import numpy as np

def cos_deg_numpy(degrees):
    return np.cos(np.deg2rad(degrees))

start_time = time.time()
for _ in range(100000):
    cos_deg_numpy(90)
end_time = time.time()

print("NumPy time:", end_time - start_time)



SymPy time: 0.6848301887512207
NumPy time: 0.09794306755065918
